import type { Cents } from "./money.js";
import type { IsoDate } from "./dates.js";
import type { Journal } from "./journals.js";
import type { PostedJournal, PostedLine, PostingOptions } from "./posting.js";

/**
 * Journals a person writes, which no amount of bank data implies.
 *
 * Everything else this app posts is derived: a bank line, an invoice, a
 * depreciation rate, a disposal. That covers a year's trading and misses the
 * part an accountant actually does at the end of it -- the judgements.
 *
 * The one that prompted this reads, in full:
 *
 *     YE26 - Remove interest expense JNL generated by Hamish.
 *     This is not a loan from directors its personal
 *
 *       437  Interest Expense    -3,354.78
 *       980  Owner Drawings       3,354.78
 *
 * Three payments had been coded to interest during the year, correctly on the
 * face of them. At year end the accountant decided the loan was personal, so
 * the interest was not deductible and the payments were drawings. Nothing in
 * the bank data says that. It is a decision, and the only honest way to carry
 * it is to record it as one.
 *
 * A manual journal must balance. That is the whole discipline of the thing: an
 * unbalanced journal is not a cautious entry, it is a broken one, and letting
 * it through would put the difference into every report that followed with
 * nothing to find it by.
 */

export interface ManualJournalLine {
  /** Account, as this ledger writes them, e.g. `Interest Expense - 437`. */
  code: string;
  /** Debit positive, credit negative. */
  amount: Cents;
  description?: string;
}

export interface ManualJournal {
  /** Stable id, so the journal can be edited and undone. */
  id: string;
  date: IsoDate;
  /**
   * Why the entry exists, in the writer's own words.
   *
   * Required, and not out of tidiness. A year later the figures are obvious
   * and the reason is not, and a journal nobody can explain is one nobody can
   * defend to an auditor.
   */
  narration: string;
  lines: ManualJournalLine[];
  /** Where it came from, when it was read out of another system. */
  source?: string;
}

/** What is wrong with a manual journal. Named apart from the report reader's. */
export interface ManualJournalProblem {
  id: string;
  message: string;
}

/** Everything wrong with a journal, or an empty list. */
export function checkManualJournal(journal: ManualJournal): ManualJournalProblem[] {
  const problems: ManualJournalProblem[] = [];
  const lines = journal.lines.filter((l) => l.amount !== 0);

  if (journal.narration.trim() === "") {
    problems.push({ id: journal.id, message: "needs a narration saying why it exists" });
  }
  if (lines.length < 2) {
    problems.push({ id: journal.id, message: "needs at least two lines with an amount" });
  }
  const total = lines.reduce((sum, l) => sum + l.amount, 0);
  if (total !== 0) {
    problems.push({
      id: journal.id,
      message: `does not balance: debits less credits is ${(total / 100).toFixed(2)}`,
    });
  }
  for (const line of lines) {
    if (line.code.trim() === "") {
      problems.push({ id: journal.id, message: "a line has no account" });
      break;
    }
  }
  return problems;
}

/**
 * Post a manual journal.
 *
 * Refuses an unbalanced one by returning null rather than posting it and
 * letting the trial balance carry the difference. The caller has already been
 * told what is wrong by `checkManualJournal`; this is the second gate, so a
 * journal that got past the first cannot reach the ledger.
 */
export function postManualJournal(
  journal: ManualJournal,
  options: PostingOptions = {},
): PostedJournal | null {
  if (checkManualJournal(journal).length > 0) return null;
  const resolve = options.resolveAccount ?? ((code: string) => ({ code, name: code }));

  const lines: PostedLine[] = journal.lines
    .filter((l) => l.amount !== 0)
    .map((line) => {
      const account = resolve(line.code);
      return {
        accountCode: account.code,
        accountName: account.name,
        amount: line.amount,
        // A manual journal carries no GST of its own. The tax was accounted
        // for when the underlying entry was made, and putting a rate on the
        // correction would claim it twice.
        taxType: "NONE" as const,
        description: line.description ?? journal.narration,
      };
    });

  return {
    transactionId: `manual:${journal.id}`,
    date: journal.date,
    narration: journal.narration,
    lines,
    source: "manual",
    taxBasis: "payments",
  };
}

/**
 * Pick the manual journals out of an imported journal report.
 *
 * An accounting system marks its own: Xero appends the source to the
 * narration, so a manual entry ends "- Manual" and a reversal begins
 * "Reversed:". Both matter -- a journal that has been reversed must not be
 * imported, or the correction is applied twice and the reversal is applied
 * never.
 */
export function manualJournalsIn(journals: readonly Journal[]): ManualJournal[] {
  const reversed = new Set<string>();
  for (const journal of journals) {
    const match = /Reversal of ID (\d+)/i.exec(journal.narration);
    if (match?.[1] !== undefined) reversed.add(match[1]);
  }

  const out: ManualJournal[] = [];
  for (const journal of journals) {
    const narration = journal.narration.trim();
    if (!/[-,]\s*Manual\b/i.test(narration)) continue;
    if (/^Reversed:/i.test(narration)) continue;
    if (reversed.has(journal.id)) continue;

    out.push({
      id: journal.id,
      date: journal.date,
      // The system's own source marker is not part of what a person wrote.
      narration: narration.replace(/\s*[-,]\s*Manual\b.*$/i, "").trim(),
      lines: journal.lines
        .filter((l) => l.amount !== 0)
        .map((l) => ({
          code: `${l.accountName} - ${l.accountCode}`.replace(/^\s*-\s*/, "").trim(),
          amount: l.amount,
          ...(l.description ? { description: l.description } : {}),
        })),
      source: "imported from the journal report",
    });
  }
  return out;
}
